export const defaultIcons = [
  // ✅ Good Habits
  { name: "fitness", setName: "Ionicons", color: "#4CAF50", type: "good" },
  { name: "book", setName: "Feather", color: "#4CAF50", type: "good" },
  {
    name: "water",
    setName: "MaterialCommunityIcons",
    color: "#4CAF50",
    type: "good",
  },
  { name: "walk", setName: "MaterialIcons", color: "#4CAF50", type: "good" },
  {
    name: "meditation",
    setName: "MaterialCommunityIcons",
    color: "#4CAF50",
    type: "good",
  },
  {
    name: "sleep",
    setName: "MaterialCommunityIcons",
    color: "#4CAF50",
    type: "good",
  },
  { name: "music", setName: "Feather", color: "#4CAF50", type: "good" },
  {
    name: "journal",
    setName: "MaterialCommunityIcons",
    color: "#4CAF50",
    type: "good",
  },
  {
    name: "healthy-food",
    setName: "MaterialCommunityIcons",
    color: "#4CAF50",
    type: "good",
  },
  { name: "running", setName: "Ionicons", color: "#4CAF50", type: "good" },
  {
    name: "yoga",
    setName: "MaterialCommunityIcons",
    color: "#4CAF50",
    type: "good",
  },
  { name: "study", setName: "Feather", color: "#4CAF50", type: "good" },
  { name: "smile", setName: "Feather", color: "#4CAF50", type: "good" },
  { name: "tree", setName: "Feather", color: "#4CAF50", type: "good" },
  { name: "sun", setName: "Feather", color: "#4CAF50", type: "good" },

  // ❌ Bad Habits
  {
    name: "smoking",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  {
    name: "beer",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  {
    name: "fast-food",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  {
    name: "tv",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  {
    name: "gaming",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  {
    name: "soda",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  {
    name: "late-night",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  {
    name: "lazy",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  { name: "shopping-bag", setName: "Feather", color: "#F44336", type: "bad" },
  {
    name: "anger",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  {
    name: "junk-food",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  {
    name: "skip-class",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  {
    name: "drugs",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  {
    name: "gossip",
    setName: "MaterialCommunityIcons",
    color: "#F44336",
    type: "bad",
  },
  { name: "mobile", setName: "Feather", color: "#F44336", type: "bad" },
];
